version: '3.4'

services:
  app:
    image: stono/ghost:latest
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    build: 
      context: .
      args:
        GCLOUD_VERSION: 264.0.0
        GHOST_VERSION: 3.8.0
        SITEMAP_GENERATOR_VERSION: 1.0.1 
    restart: always
    environment:
      NODE_ENV: production
      GHOST_DOMAIN: karlstoney.com
    volumes:
      - ./data/content/data:/var/www/ghost/current/content/data
      - ./data/content/images:/var/www/ghost/current/content/images
      - ./data/content/settings:/var/www/ghost/current/content/settings
      - ./bin:/usr/local/bin
      - ~/.config:/root/.config:ro
      - ./data/static:/static
    ports:
      - 80:80
