version: '3.4'

services:
  app:
    image: stono/ghost:latest
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    build: 
      context: .
      args:
        GHOST_VERSION: 4.22.0
        GHOST_CLI_VERSION: 1.18.0
        SITEMAP_GENERATOR_VERSION: 1.0.1
        NODEJS_VERSION: 16
        GCLOUD_VERSION: 364
        ARCH: arm
    restart: always
    environment:
      NODE_ENV: production
      GHOST_DOMAIN: karlstoney.com
    volumes:
      - ./data/content/data:/var/www/ghost/current/content/data
      - ./data/content/images:/var/www/ghost/current/content/images
      - ./data/content/settings:/var/www/ghost/current/content/settings
      - ./data/static:/static
    ports:
      - 80:80
