version: '3.4'

services:
  app:
    image: stono/ghost:latest
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    build: 
      context: .
      args:
        GCLOUD_VERSION: 227.0.0
        GHOST_VERSION: 2.9.1
        SITEMAP_GENERATOR_VERSION: 0.0.11
    restart: always
    extra_hosts:
      - "karlstoney.com:127.0.0.1"
    environment:
      NODE_ENV: production
    volumes:
      - ./data/content/data:/var/www/ghost/current/content/data
      - ./data/content/images:/var/www/ghost/current/content/images
      - ./data/content/settings:/var/www/ghost/current/content/settings
      - ~/.config:/root/.config:ro
    ports:
      - 80:80
